project:
  type: book

book:
  title: "Intro Pred Model Portfolio"
  author: "Liane Emmim"
  date: "5/22/2026"
  chapters:
    - hw1.qmd
    - hw2.qmd
    - hw3.qmd
    - hw4.qmd
    - hw5.qmd
  
format:
  html:
    theme:
      - cosmo
      - brand




